export const exerciseTypeMap: Record<number, string> = {
    0: "Other Workout",
    2: "Badminton",
    4: "Baseball",
    5: "Basketball",
    8: "Biking",
    9: "Stationary Biking",
    10: "Boot Camp",
    11: "Boxing",
    13: "Calisthenics",
    14: "Cricket",
    16: "Dancing",
    25: "Elliptical",
    26: "Exercise Class",
    27: "Fencing",
    28: "Football (American)",
    29: "Football (Australian)",
    31: "Frisbee Disc",
    32: "Golf",
    33: "Guided Breathing",
    34: "Gymnastics",
    35: "Handball",
    36: "HIIT",
    37: "Hiking",
    38: "Ice Hockey",
    39: "Ice Skating",
    44: "Martial Arts",
    46: "Paddling",
    47: "Paragliding",
    48: "Pilates",
    50: "Racquetball",
    51: "Rock Climbing",
    52: "Roller Hockey",
    53: "Rowing",
    54: "Rowing Machine",
    55: "Rugby",
    56: "Running",
    57: "Running (Treadmill)",
    58: "Sailing",
    59: "Scuba Diving",
    60: "Skating",
    61: "Skiing",
    62: "Snowboarding",
    63: "Snowshoeing",
    64: "Soccer",
    65: "Softball",
    66: "Squash",
    68: "Stair Climbing",
    69: "Stair Climbing Machine",
    70: "Strength Training",
    71: "Stretching",
    72: "Surfing",
    73: "Swimming (Open Water)",
    74: "Swimming (Pool)",
    75: "Table Tennis",
    76: "Tennis",
    78: "Volleyball",
    79: "Walking",
    80: "Water Polo",
    81: "Weightlifting",
    82: "Wheelchair",
    83: "Yoga",
};

export function getExerciseName(typeCode: number): string {
    return exerciseTypeMap[typeCode] || `Unknown Exercise (${typeCode})`;
}